### ISSUE TITLE
Uniformly distribute classification

### ISSUE THREAD

**Issue by loleg** [Streetwise/streetwise-app#18]
Currently the images are returned using a random call to the database, which does not ensure that images are homogeneously evaluated although the distribution should be relatively even. This is being discussed with the data science team. Please add comments here if you:

- Know of a good strategy to take in the context of a citizen science project*
- Can suggest a way to sort / query our database randomly in an efficient way
- Have an idea of how to visualize or measure the distribution of our results

(*) For a good overview of Python randomness, see the chapters on [Random numbers](http://people.duke.edu/~ccc14/sta-663-2017/15A_Random_Numbers.html), [Quasi-randomness](http://people.duke.edu/~ccc14/sta-663-2017/15C_MonteCarloIntegration.html#quasi-random-numbers) and [Pseudorandom number generators](http://people.duke.edu/~ccc14/sta-663-2016/15A_RandomNumbers.html) in the Computational Statistics and Statistical Computing course from Duke University.

**Comment by loleg** [comment]
The approach I would take is to set a variable goal for each image (e.g. 20?), keep a tally, and stop showing the image once it has been evaluated (shown?) enough times.

**Comment by colombmo** [comment]
> The approach I would take is to set a variable goal for each image (e.g. 20?), keep a tally, and stop showing the image once it has been evaluated (shown?) enough times.

This would work, but it has the disadvantage that it creates an upper bound to the number of comparisons that can be done.
Continuing to select couples of pictures at random should, theoretically, provide a more or less equally distributed number of comparisons for each picture. 

However, a solution to force the number of comparisons to be even more similar, would be to use some weights, decreasing based on the number of times a picture has been compared, for example with something like (in python) random.choices([img1, img2, img3, img4], weights=[1/n_img1, 1/n_img2, 1/n_img3, 1/n_img4]), where n_imgx corresponds to the number of times image x has been used. This way, the more a picture has been used, the less it is probable to be selected in the random selection, giving priority to the least used pictures. Obviously n_imgx should in this case start at 1 to prevent divisions by 0, and be increased at each time imgx is selected.

**Comment by yudistrange** [comment]
We can modify what @loleg suggested by having a `count` column in the images table. It will keep track of how many times this image has been shown to the user. 

While querying the db for images, we should sort the rows by this column and fetch the first x rows. The app then selects 2 out of these x rows and displays them to the user. This process can also be done in the db, if we introduce some randomness in the order as well (otherwise we will end up serving the same pair of images)

Something along the lines:
`select * from images order by count, random() fetch first 2 rows only`

**Comment by loleg** [comment]
That's almost how our ORM-based [query works](https://github.com/Streetwise/streetwise-app/blob/a8e49284da523827cc96b46b71a2639d6e39e81e/streetwise/api/images.py#L48) now. Feel free to give that approach a try!

**Comment by yudistrange** [comment]
I can come up with three approaches to make the image distribution more uniform.

1. Create an in-memory dict that maintains the mapping of image-id to number of times it has been served.

2. Add a count column in the `images` table in database to maintain the same number

3. Create a table to keep track of image id to count mapping

I will try and list down the pros and cons for all the three approaches

**In memory dict approach**
_Pros_
- Can be implemented quite trivially

_Cons_
- The dict will need to be populated at the app start up time
- The size of the dict will increase linearly with the no. of images. Thus we can potentially create memory pressure on the app

**Adding count column to `images` database**
_Pros_
- Trivial to implement

_Cons_
- The approach will add additional load on the database
- It is not extensible. The count is bound to images, we may later want to count images shown by campaign, which may require complete rework

**Adding a new table to keep track of image display counts**
_Pros_
- The approach can be extended to allow counting of images per campaign or any other metric

_Cons_
- The search for least shown images will require a join query
- There will be additional load on the database because of additional writes

**Comment by loleg** [comment]
Thanks for documenting the approaches. My vote is for option 1, with some thought put in now about replacing the in-memory variable with a Redis key/value store.
