### ISSUE TITLE
Support multiple campaigns

### ISSUE THREAD

**Issue by loleg** [Streetwise/streetwise-app#41]
In the data model we have support for a `Campaign` data type, and now we need to complete support in the app for running sessions for differing campaigns, the contents for which will be defined in the next days. 

A campaign currently represents:

- Introductory content (`Start`)
- The question asked above the image voting (`ImageVote`)
- Content in the help box (`Wiser`)
- Content in the finish screen (`Complete`, to be confirmed)
- A collection of images (to be confirmed)
- Feedback form (to be confirmed)

We want to assign users to one or another campaign based on some criteria (weighted random factor, and/or a cookie in their browser). We may want to switch campaigns in the same session (advised against it, but to be confirmed).

**Comment by loleg** [comment]
Work in progress in the [multi-campaign branch](https://github.com/Streetwise/streetwise-app/tree/41-multi-campaign)

**Comment by yudistrange** [comment]
Couple of questions:

- To pass around the campaign id to different routes, I think we are going to pass it along as a query parameter (check the props: true in router.js). But that would allow the users to change the campaign by changing the url. Should we try doing this using local store / cookies instead?

- I think we should modify the campaign database table to store the information that unique to a campaign (Eg. question on the wiser, introductory content etc). Otherwise we would have to make a code change every time we roll out a new campaign.

**Comment by loleg** [comment]
- We'll let the backend decide, fetching the "next campaign" value each time a voting session starts.
- Currently all the app's text content is in the code and requires a deployment. Let's keep it 'static'. I've suggested a way of using YAML for campaign specific content.

**Comment by loleg** [comment]
Deployed to stage for testing.

**Comment by loleg** [comment]
Final release, with additional refactoring, is in stage.
