### ISSUE TITLE
Vote export API fails on multiple campaigns

### ISSUE THREAD

**Issue by yudistrange** [Streetwise/streetwise-app#62]
The failure happens for the following APIs
- /results/all
- /results/undecided

The API to fetch the latest vote works as expected.

**Comment by yudistrange** [comment]
Our migration to add campaign id to the votes table was insufficient. After running this migration in testing db, the votes table ended up with rows that did not have any campaign information attached to them.

This has been fixed in prod by adding a default campaign id to the older votes.

**Comment by loleg** [comment]
The migration command [from this commit](https://github.com/Streetwise/streetwise-app/commit/6aae51d2f0a47d431e83932872c59910b43f8b29#diff-342189d3c44e5ebcbdf5dee27da30f89R23) can also be run manually, though I don't see any reason why it should fail.

@yudistrange if this issue is specifically for the missing campaign value, and if you've solved it in the DB, then please close this issue.

**Comment by yudistrange** [comment]
Afaik the migration was run on stage and not production. I will check and run the migration.
Will close the issue post that.

**Comment by yudistrange** [comment]
This is fixed.
